[package]
name = "player"
version = "0.1.0"
edition = "2021"

[dependencies]
sid_file.workspace = true
mos6510.workspace = true

anyhow = "1.0"
resid-rs = { path = "../../resid-rs" }
clap = { version="4.5", features = ["derive"] }
cpal = "0.15"
ringbuf = "0.4"
spinners = "4.1"
inline_colorization = "0.1.6"
